### ISSUE TITLE
Update events are missing for some attributes

### ISSUE THREAD

**Issue by mwittig** [bstrebel/pimatic-phone#3]
Update events are missing for location, position, previousLocation, and previousPosition. Thus frontend views and rule predicates for these attributes will not be properly updated / triggered. See also https://forum.pimatic.org/topic/2932/solved-pimatic-phone-presence-sensor-not-updated-by-rule

I think it is a flaw in the current implementation. Normally, each attribute value is held by an instance variable, e.g. "_tag" for the "tag" attribute value. However, this is not the case for "location" as this attribute simply is an alias for "tag", i.e., getLocation() provides the "_tag" value. 

The problem is the [update handler](https://github.com/bstrebel/pimatic-phone/blob/master/phone.coffee#L760-L768) for attribute values which only triggers update events for attributes which have an "_<attribute>" instance variable - which is not the case for location, position, previousLocation, and previousPosition. To mitigate the problem the _emitUpdates() needs to be partially rewritten, or the alias attributes need to removed.

**Comment by bstrebel** [comment]
Fixed with v0.9.6: _emitUpdates() changed to handle alias attributes correctly
