### ISSUE TITLE
Error after Pimatic update to version 0.9.44

### ISSUE THREAD

**Issue by mathiaslehmann** [bstrebel/pimatic-phone#6]
Hello, I have a problem with the Phone Plugin after the Pimatic update to version 0.9.44. Here is my log at startup. An error “Cannot find module ‘i18n’” appears. Can someone help here? Thank you. 

18:25:45.550 [pimatic] info: Loading plugin: “pimatic-phone” (0.9.6)
18:25:45.662 [pimatic] error: Cannot find module ‘i18n’

**Comment by michbeck100** [comment]
Did you try to remove the plugin and reinstall? It might install `i18n` properly then. Don't forget to save your config though.

**Comment by mathiaslehmann** [comment]
Hello, I've tried that now. The error remains unfortunately.

**Comment by bstrebel** [comment]
Hi, at the moment I'm not able to update my development environment to 0.9.44. It would be great, if @michbeck100 could help with the module loading problem.

**Comment by michbeck100** [comment]
@bstrebel Why are you using 18n at all? I don't see that you have any translations in the project, and pimatic core doesn't include translations for pimatic-phone either.

**Comment by michbeck100** [comment]
#7 solves the issues

**Comment by bstrebel** [comment]
Published 0.9.7 with fix from @michbeck100
